version: '3.8'

services:
  forticlient-vpn:
    build: .
    image: forticlient-vpn-gui:latest
    container_name: forticlient-vpn-gui
    restart: "no"
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:ro
      - ./config/forti.conf:/etc/swanctl/conf.d/forti.conf
