#!/bin/bash
set -e

mkdir -p /etc/swanctl/conf.d

SUDOERS_FILE="/etc/sudoers.d/forticlient-vpn"
cat << 'EOF' > "$SUDOERS_FILE"
ALL ALL=(root) NOPASSWD: /usr/sbin/swanctl --load-all
ALL ALL=(root) NOPASSWD: /usr/sbin/swanctl --list-sas
ALL ALL=(root) NOPASSWD: /usr/sbin/swanctl --initiate --child forticlient
ALL ALL=(root) NOPASSWD: /usr/sbin/swanctl --terminate --ike forticlient
ALL ALL=(root) NOPASSWD: /usr/bin/tee /etc/swanctl/conf.d/forti.conf
ALL ALL=(root) NOPASSWD: /usr/bin/chmod 600 /etc/swanctl/conf.d/forti.conf
ALL ALL=(root) NOPASSWD: /usr/bin/mkdir -p /etc/swanctl/conf.d
ALL ALL=(root) NOPASSWD: /bin/systemctl start strongswan-starter.service
ALL ALL=(root) NOPASSWD: /usr/bin/systemctl start strongswan-starter.service
ALL ALL=(root) NOPASSWD: /bin/systemctl start strongswan.service
ALL ALL=(root) NOPASSWD: /usr/bin/systemctl start strongswan.service
ALL ALL=(root) NOPASSWD: /usr/sbin/ip rule add lookup 220 pref 220
ALL ALL=(root) NOPASSWD: /sbin/ip rule add lookup 220 pref 220
EOF
chmod 0440 "$SUDOERS_FILE"
chown root:root "$SUDOERS_FILE"

chmod +x /usr/share/forticlient-vpn/vpn-gui.py
